mutation CREATE_MEMBER($firstName: String!, $lastName: String!, $bio: _Text!, $birthday: _Datetime!, $phone: String!, $email: String!, $title: String!, , $skills: [String]!, $avatar: String!) {
  __typename
  MemberCreate(input: {firstName: $firstName, lastName: $lastName, bio: $bio, birthday: $birthday, avatar: {url: $avatar}, phone: $phone, skills: $skills, title: $title, email: $email, active: true}) {
    id
    active
    firstName
    lastName
    title
    staff
    skills
  }
}
